name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: make install

    - name: Lint with flake8
      run: make lint

    - name: Run tests
      run: make test
